# Generated by Django 3.1.4 on 2021-01-14 18:40

from django.db import migrations


def clean_tmp_topologies(apps, schema_editor):
    Topology = apps.get_model('core', 'topology')
    Topology.objects.filter(kind__in=('TMP', 'TOPOLOGY')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201117_1302'),
    ]

    operations = [
        migrations.RunPython(clean_tmp_topologies),
    ]
